test_that(".prefix_zero works", {
    expect_equal(.prefix_zero(54), "54")
    expect_equal(.prefix_zero(c(1, 100)), c("001", "100"))
})

test_that(".resolve_fun works", {
    expect_error(.resolve_fun(NA), "Can not")
    expect_error(.resolve_fun(c("other")), "Can not")
    expect_error(.resolve_fun(c("MS:1002883", "other")), "Can not")
    res <- .resolve_fun("MS:1002883")
    expect_length(res, 1L)
    expect_true(is.list(res))
    expect_true(is.function(res[[1L]]))
    expect_equal(res[[1L]], median)
    res <- .resolve_fun(c("MS:1002883", "MS:1002962"))
    expect_length(res, 2L)
    expect_true(is.list(res))
    expect_true(is.function(res[[1L]]))
    expect_equal(res[[1L]], median)
    expect_true(is.function(res[[2L]]))
    expect_equal(res[[2L]], mean)
})

test_that("parse_cv_parameter works", {
    x <- c("aaa", "[aaaa]")
    expect_error(parse_cv_parameter(x), "Unexpected CV")
    res <- parse_cv_parameter(c("[a,b,c,d]", "[e, f, g, h]"), 1L)
    expect_equal(res, c("a", "e"))
    res <- parse_cv_parameter(c("[a,b,c,d]", "[e, f, g, h]"), 2L)
    expect_equal(res, c("b", "f"))
    res <- parse_cv_parameter(c("[a,b,c,d]", "[e, f, g, h]"), 3L)
    expect_equal(res, c("c", "g"))
    res <- parse_cv_parameter(c("[a,b,c,d]", "[e, f, g, h]"), 4L)
    expect_equal(res, c("d", "h"))

    res <- parse_cv_parameter(c("[a, , , ]", "[b,,,]"), 1L)
    expect_equal(res, c("a", "b"))
    res <- parse_cv_parameter(c("[a, , , ]", "[b,,,]"), 2L)
    expect_equal(res, c(NA_character_, NA_character_))
    res <- parse_cv_parameter(c("[a, , , ]", "[b,,,]"), 3L)
    expect_equal(res, c(NA_character_, NA_character_))
    res <- parse_cv_parameter(c("[a, , , ]", "[b,,,]"), 4L)
    expect_equal(res, c(NA_character_, NA_character_))
})
