## Code related to import/export of the SML table

## internal notes:
##
## - Create SML from user provided info
## - have a helper function that links between SMF and SML?
## - SML should be a subset of the SMF
## - SML should also contain averages/variation for the study variables
##   (defined in the MTD section)
##

################################################################################
##    Create SML section
##
################################################################################

#' @title Creating the mzTab-M Small Molecule (SML) Table
#'
#' @name SML-export
#'
#' @aliases sml_create
#'
#' @aliases sml_sort
#'
#' @description
#'
#' The Small Molecule (SML) table is mandatory in the mzTab-M format and
#' provides abundances along with annotations on the small molecules of an
#' analysis result. All columns in this table need to be tab-delimited and no
#' empty cells are allowed (`"null"` must be used for missing values, for
#' columns that support that).
#'
#' Each row of the small molecule section is intended to report one final result
#' to be communicated in terms of a molecule that has been quantified. In many
#' cases, this may be the molecule of biological interest. In general, different
#' adduct forms for the same molecule would be reported in the *Small Molecule
#' Feature* (SMF) section.
#'
#' A detailed description of the SML format and its columns is provided in the
#' [respective section](https://github.com/HUPO-PSI/mzTab-M/blob/main/specification_documents/mzTab_format_specification_2_1-M.adoc#63-small-molecule-section)
#' of the mzTab-M specification.
#'
#' The functions to create and format the SML content are:
#'
#' - `sml_create()`: main function that creates the SML table based on the
#'   provided abundance matrix and small molecule annotation information.
#'
#'   The function automatically:
#'
#'   - Formats the abundance matrix `x` (renaming column names to
#'     `"abundance_assay[n]"`)
#'   - Adds the required `"SML_ID"` column with a running integer representing
#'     the primary key (unique ID) for each molecule.
#'   - Populates missing mandatory columns with `"null"` strings.
#'   - Sets the line prefix column.
#'   - Orders the columns according to the mzTab-M specification.
#'
#'   After `sml_create()` required study variable abundance columns should
#'   be either added manually or using the [sml_add_study_variable_columns()]
#'   function. These required columns contain the average and variation
#'   of molecule abundances across samples of a particular study variable.
#'
#' - `sml_add_study_variable_columns()`: *completes* the SML table created
#'   with `sml_create()` by adding columns with aggregated assay values
#'   (molecule abundances) per study variable(s). Study variables have to be
#'   listed in the MTD section provided with the `mtd` parameter (e.g.
#'   `"study_variable[1]"`) where also the aggregation functions must be
#'   defined (e.g. `"study_variable[1]-average_function"`). This aggregation
#'   and variation functions has to be defined using the respective MS CV
#'   ontology term (e.g. `"MS:1002962"` for the mean and `"MS:1002963"` for
#'   the coefficient of variation). See [MTD-export] for details on the MTD
#'   section.
#'
#'   The function:
#'
#'   - gets all study variables from the metadata section (`mtd`)
#'     - for each study variable:
#'     - gets the assay references from MTD
#'     - gets the summary functions (for average and variation) from MTD
#'       (resolving the MS CV term to the respective R function)
#'     - gets the referred abundance columns in `x`
#'     - calculates the summary statistic and these as additional columns to
#'       `x`.
#'
#' - `sml_sort()`: sorts the columns of an SML table into the expected order.
#'
#' @param ... optional columns to be added to the SML. The length of arguments
#'     passed through `...` has to match `nrow(x)` and the arguments **have**
#'     to be named. The name of the argument is used for the column name,
#'     prefixed with `"opt_"`.
#'
#' @param x for `sml_create()`: `matrix` or `data.frame` with the abundances
#'     of the small molecules. Only the abundances of the molecules should be
#'     reported (rows being molecules, columns samples).
#'     For `sml_add_study_variable_columns()`: `data.frame` generated by
#'     `sml_create()`.
#'     For `sml_sort()`: a SML `data.frame`, such as created by `sml_create()`.
#'
#' @param SMF_ID_REFS `character` with the index (ID) of all features (rows in
#'     the SMF matrix) each small molecule bases on. The length of the input
#'     has to match `nrow(x)`. If not provided, `"null`" is assigned to all
#'     molecules. Multiple IDs for one molecule can be separated by `"|"`.
#'
#' @param database_identifier `character` with the identifier of the molecule.
#'     Has to be in the format *<SOURCE>:<ID>* to provide the database/source
#'     of annotation and the ID (e.g. `"HMDB:HMDB0001847"`). Multiple values
#'     can be concatenated using `"|"`.
#'     Can be `"null"` or `NA` for molecules without annotations. The length
#'     of `database_identifier` has to match the number of rows of `x`. If not
#'     provided (the default) `"null"` is assigned to each row/molecule.
#'
#' @param chemical_formula `character` with the (possible) chemical formula(s)
#'     of the compound. Can be `"null"` but, if provided, its length has to
#'     match the number of rows of `x`. Multiple formulas have to be
#'     concatenated with `"|"` and the number of formulas per molecule **have**
#'     to match the number of reported identifiers in `database_identifier`.
#'
#' @param smiles `character` with the potential molecule structures in the
#'     simplified molecular-input line-entry system (SMILES) for the small
#'     molecule. Can be `"null"` but, if provided, its length has to match the
#'     number of rows of `x`. The number of smiles per molecule **must**
#'     match the number of reported identifiers in `database_identifier` and
#'     have to be separated by `"|"`.
#'
#' @param inchi `character` with the potential standard IUPAC International
#'     Chemical Identifier (InChI) of the given substance. Can be `"null"` but,
#'     if provided, its length has to match the number of rows of `x`.
#'     The number of inchis per molecule **must** match the number of reported
#'     identifiers in `database_identifier` and have to be separated by `"|"`.
#'
#' @param chemical_name `character` with the possible chemical/common names for
#'     the small molecule, or general description if a chemical name is
#'     unavailable. Can be `"null"` but, if provided, its length has to match
#'     the number of rows of `x`. The number of names provided **must**
#'     match the number of entities reported under `database_identifier` and
#'     have to be separated by `"|"`.
#'
#' @param uri `character` with the URI pointing to the small molecule’s entry
#'     in a reference database (e.g., the small molecule’s HMDB or KEGG entry).
#'     Can be `"null"` but, if provided, its length has to match the number of
#'     rows of `x`.
#'     The number of uris per molecule **must** match the number of reported
#'     identifiers in `database_identifier` and have to be separated by `"|"`.
#'
#' @param theoretical_neutral_mass `numeric()` with the small molecule's
#'     precursor's theoretical **neutral** mass. Can be `NA` but,
#'     if provided, its length has to match the number of rows of `x`.
#'     The number of masses per molecule **must** match the number of reported
#'     identifiers in `database_identifier` and have to be separated by `"|"`.
#'
#' @param adduct_ions `character()` with a `"|"` separated list of detected
#'     adducts for this this molecule. Can be `"null"` (or `NA`) but, if
#'     provided, its length has to match the number of rows of `x`.
#'
#' @param reliability `character()` or `integer()` of length equal to `nrow(x)`
#'     with the reliability of annotation following one of the supported
#'     schemas. Has to be of length equal to `nrow(x)`. `"null"` or `NA` are
#'     allowed if no reliability information is available.
#'
#' @param best_id_confidence_measure `character()` defining the approach or
#'     database search that identified the molecule with highest confidence. Has
#'     to be a CV parameter, but can also be `"null"` or `NA` if not available.
#'     If provided, the length has to match `nrow(x)`.
#'
#' @param best_id_confidence_value `numeric()` the value/score of the best
#'     confidence measure. If provided, the length has to match `nrow(x)`. The
#'     type of score **must** be defined in the metadata section. Can also be
#'     `NA` if not available.
#'
#' @param mtd two-column `matrix` or `data.frame` with the metadata (MTD)
#'     definition of the data set. The first column needs to contain the
#'     metadata field names, the second the corresponding values. See
#'     [MTD-export] help page for more information.
#'
#' @return
#'
#' For `sml_create()`: a `character` `data.frame` ready for export. The
#' `data.frame` contains the `"SMH"` line prefix, the standard columns ordered
#' according to the mzTab-M specification, the abundance columns, the
#' abundance columns aggregated per study variables and any optional columns.
#'
#' For `sml_sort()`: the input `data.frame` with columns ordered as defined
#' by the mzTab-M definition.
#'
#' @details
#'
#' All parameters passed to the `sml_create()` function must be **fully named**.
#'
#' @author Johannes Rainer
#'
#' @examples
#'
#' ## Define an example abundance matrix
#' amat <- matrix(abs(rnorm(20)), ncol = 4, nrow = 5)
#' colnames(amat) <- c("sample_1", "sample_2", "sample_3", "sample_4")
#'
#' ## Define annotation information for each row (molecule). This information
#' ## should be the result of an annotation pipeline used.
#' anns <- data.frame(
#'     hmdb_id = c("HMDB:HMDB0001847",
#'                 NA,
#'                 "HMDB:HMDB0000122|HMDB:HMDB0000169",
#'                 "HMDB:HMDB0000258",
#'                 "HMDB:HMDB0060475"),
#'     formula = c("C8H10N4O2",
#'                 NA,
#'                 "C6H12O6|C6H12O6",
#'                 "C12H22O11",
#'                 "C5H9NO4"),
#'     smiles = c("CN1C=NC2=C1C(=O)N(C)C(=O)N2C",
#'                NA,
#'                "OC[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@@H]1O|OC[C@H]1O[C@H](O)[C@@H](O)[C@@H](O)[C@@H]1O",
#'                NA,
#'                "NC(CCC(O)=O)C(O)=O"),
#'     neutral_mass = c(194.0804, NA, "180.0634|180.0634", 342.1162, 147.0531),
#'     name = c("caffeine", NA, "glucose|mannose", "sucrose", "DL-Glutamate"),
#'     adduct_ions = c("[M+H]1+", NA, "[M+Na]1+",
#'                     "[M+H]1+", "[M+H]1+"),
#'     uri = c("http://www.hmdb.ca/metabolites/HMDB0001847",
#'             NA,
#'             "http://www.hmdb.ca/metabolites/HMDB0000122|http://www.hmdb.ca/metabolites/HMDB0000169",
#'             "http://www.hmdb.ca/metabolites/HMDB0000258",
#'             "http://www.hmdb.ca/metabolites/HMDB0060475"))
#'
#' ## Create the SML table based on this information. Note that we have to
#' ## use the **full** name for **all** function arguments (i.e., `x = amat`
#' ## etc).
#' sml <- sml_create(
#'     x = amat, database_identifier = anns$hmdb_id,
#'     chemical_formula = anns$formula, smiles = anns$smiles,
#'     theoretical_neutral_mass = anns$neutral_mass, uri = anns$uri,
#'     chemical_name = anns$name, adduct_ions = anns$adduct_ions)
#' sml
#'
#' ## Update the reference between rows in SML with those in an SMF table
#' sml$SMF_ID_REFS <- c("3", "5", "8|23", "12", "16")
#'
#' ## Re-order columns in the expected order
#' sml <- sml_sort(sml)
#' sml
#'
#' ## Add study variable abundace columns based on study variable definition
#' ## in a metadata (MTD) section.
#' ## In the example below we first define a metadata section with the
#' ## minimally required information for `sml_add_study_variable_columns()`:
#' ## the study variables, the samples (assays) that belong to each and
#' ## a average and variation function (see ?MTD-export for full help on the
#' ## metadata section).
#' ## In the example we assign sample 1 and 3 to the `"male"` category/study
#' ## variable and 2 and 4 to `"female"`. For the average and variation
#' ## function we use the mean and coefficient of variation.
#' mtd <- cbind(
#'     c("study_variable[1]",
#'       "study_variable[1]-assay_refs",
#'       "study_variable[1]-average_function",
#'       "study_variable[1]-variation_function",
#'       "study_variable[1]-description",
#'       "study_variable[2]",
#'       "study_variable[2]-assay_refs",
#'       "study_variable[2]-average_function",
#'       "study_variable[2]-variation_function",
#'       "study_variable[2]-description"),
#'     c("male",
#'       "assay[1]|assay[3]",
#'       "[MS, MS:1002962, mean, ]",
#'       "[MS, MS:1002963, variation coefficient, ]",
#'       "sex of participants, male",
#'       "female",
#'       "assay[2]|assay[4]",
#'       "[MS, MS:1002962, mean, ]",
#'       "[MS, MS:1002963, variation coefficient, ]",
#'       "sex of participants, female")
#' )
#' ## Add study variable average and variation columns and sort the columns
#' sml <- sml_add_study_variable_columns(sml, mtd) |> sml_sort()
#' sml
#'
#' ## The average and variation for each study variable were calculated from
#' ## the assay abundances and added as additional columns to the SML.
#' @export
sml_create <- function(..., x,
                       SMF_ID_REFS = character(),
                       database_identifier = character(),
                       chemical_formula = character(),
                       smiles = character(),
                       inchi = character(),
                       chemical_name = character(),
                       uri = character(),
                       theoretical_neutral_mass = numeric(),
                       adduct_ions = character(),
                       reliability = character(),
                       best_id_confidence_measure = character(),
                       best_id_confidence_value = character()) {
    x <- .abundance_matrix(x, id_col = "SML_ID")
    nr <- nrow(x)
    x <- cbind(SMH = rep("SML", nr), x)
    ## SMF_ID_REFS, can be null, can be | separated
    x$SMF_ID_REFS <- .check_fill_column(SMF_ID_REFS, lout = nr)
    ## database_identifier: can be | separated or null; all following column
    ## need to have the same number of | separated values
    did <- .check_fill_column(database_identifier, lout = nr)
    ls <- lengths(strsplit(did, split = "|", fixed = TRUE))
    x$database_identifier <- did
    x$chemical_formula <- .check_fill_column(chemical_formula, nr, lengths = ls)
    x$smiles <- .check_fill_column(smiles, nr, lengths = ls)
    x$inchi <- .check_fill_column(inchi, nr, lengths = ls)
    x$chemical_name <- .check_fill_column(chemical_name, nr, lengths = ls)
    x$uri <- .check_fill_column(uri, nr, lengths = ls)
    x$theoretical_neutral_mass <- .check_fill_column(theoretical_neutral_mass,
                                                     nr, lengths = ls)
    ## The following do not need to match database_identifier
    x$adduct_ions <- .check_fill_column(adduct_ions, nr)
    x$reliability <- .check_fill_column(reliability, nr)
    ## Should be a CV parameter
    x$best_id_confidence_measure <- .check_fill_column(
        best_id_confidence_measure, nr)
    ## HAS to be reported in MTD!
    x$best_id_confidence_value <- .check_fill_column(
        best_id_confidence_value, nr)
    ## Add optional columns
    x <- .add_opt_cols(x = x, ...)
    sml_sort(x)
}

#' @export
#'
#' @rdname SML-export
sml_sort <- function(x) {
    x[, .sort_order(colnames(x), .SML_ORDER), drop = FALSE]
}

#' @description
#'
#' Standard SML column order defined by the mzTab-M specification.
#'
#' @noRd
.SML_ORDER <- c(
    "^SMH",
    "^SML_ID",
    "^SMF_ID_REFS",
    "^database_identifier",
    "^chemical_formula",
    "^smiles",
    "^inchi",
    "^chemical_name",
    "^uri",
    "^theoretical_neutral_mass",
    "^adduct_ions",
    "^reliability",
    "^best_id_confidence_measure",
    "^best_id_confidence_value",
    "^abundance_assay\\[\\d+\\]$",
    "^abundance_study_variable\\[\\d+\\]$",
    "^abundance_variation_study_variable\\[\\d+\\]$",
    "^opt_"
)

#' @rdname SML-export
#'
#' @export
sml_add_study_variable_columns <- function(x, mtd) {
    svars <- .mtd_get_field(mtd, "study_variable\\[\\d.*\\]$",
                            exact = FALSE, fixed = FALSE)[[1L]]
    ## iterate over study variables and add columns
    for (svname in names(svars)) {
        sv <- .mtd_get_field(mtd, svname, exact = FALSE)[[1L]]
        if (is.na(aref <- sv[paste0(svname, "-assay_refs")]))
            stop("Field \"", svname, "-assay_ref\" missing in 'mtd'")
        aref <- strsplit(aref, split = "|", fixed = TRUE)[[1L]]
        acols <- paste0("abundance_", aref)
        cnx <- colnames(x)
        if (!all(acols %in% cnx))
            stop("Columns ", paste0("\"", acols[!acols %in% cnx],
                                    "\"", collapse = ", "),
                 " not found in 'x'")
        ## Get the average function.
        if (is.na(savg <- sv[paste0(svname, "-average_function")]))
            stop("Field \"", svname, "-average_function\" missing in 'mtd'")
        if (is.na(svar <- sv[paste0(svname, "-variation_function")]))
            stop("Field \"", svname, "-variation_function\" missing in 'mtd'")
        ## Get the CV term and throw an error if it's not supported.
        if (is.na(savg_cv <- parse_cv_parameter(savg, 2L)))
            stop("\"", savg, "\" lacks a CV term/accession. Can not process.")
        if (is.na(svar_cv <- parse_cv_parameter(svar, 2L)))
            stop("\"", svar, "\" lacks a CV term/accession. Can not process.")
        x <- cbind(x, apply(x[, acols, drop = FALSE], MARGIN = 1,
                            FUN = .resolve_fun(savg_cv)[[1L]]))
        cnx <- c(cnx, paste0("abundance_", svname))
        colnames(x) <- cnx
        x <- cbind(x, apply(x[, acols, drop = FALSE], MARGIN = 1,
                            FUN = .resolve_fun(svar_cv)[[1L]]))
        colnames(x) <- c(cnx, paste0("abundance_variation_", svname))
    }
    x
}

################################################################################
##    Parse SML section
##
################################################################################
